apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hello-function
  name: hello-function-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-function
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-function
    spec:
      containers:
      - image: triathlonguy/hello-function:jvm
        imagePullPolicy: IfNotPresent
        env:
          - name: TARGET
            value: from-Kubernetes-deployed-function
        name: app


