apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello-function
  namespace: hello-function
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: triathlonguy/hello-function:jvm
      creationTimestamp: null
      name: hello-function-v1
    spec:
      containerConcurrency: 25
      containers:
      - env:
        - name: TARGET
          value: from Serverless Test - Spring Function on JVM
        image: triathlonguy/hello-function:jvm
        name: user-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
